services:
  traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK?TRAEFIK_NETWORK must be set}"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      
      # HTTP to HTTPS redirect
      - "traefik.http.routers.dashboard-http.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN?TRAEFIK_DASHBOARD_DOMAIN must be set}`)"
      - "traefik.http.routers.dashboard-http.entrypoints=http"
      - "traefik.http.routers.dashboard-http.middlewares=redirect-https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      
      # HTTPS with Basic Auth
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN?TRAEFIK_DASHBOARD_DOMAIN must be set}`)"
      - "traefik.http.routers.dashboard.entrypoints=${TRAEFIK_ENTRYPOINT?TRAEFIK_ENTRYPOINT must be set}"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      
      # Basic Auth middleware
      - "traefik.http.middlewares.auth.basicauth.usersfile=/auth.txt"
    
    volumes:
      - ./auth.txt:/auth.txt:ro
